### ISSUE TITLE
On the case of no smooth minimal points

### ISSUE THREAD

**Issue by RecursionSheep** [ACSVMath/sage_acsv#11]
I am using sage-acsv to compute the asymptotics of some generating functions. I found that in the multivariate case, it is possible that no minimal critical points exist, e.g., 1 / (1 - y - x * y^3). Does this mean that the asymptotics is sub-exponential?

```
var('x y')
F = 1 / (1 - y - x * y ^ 3)
diagonal_asy(F)
......
ACSVException: No smooth minimal critical points found.
```

**Comment by smelczer** [comment]
**Short answer:** 

No, you can't conclude that in general.

**Long answer:**

Theoretically, there are a few reasons you could have no smooth minimal critical points:

1) You could have minimal critical points that are non-smooth.

2) You could have no minimal critical points, but have critical points that are non-minimal.

3) You could have "critical points at infinity" which are sequences of points that become critical points in a limiting sense.

4) You could have no critical points or critical points at infinity.

In situation 4 only, you can always conclude that your sequence decays super-exponentially. In fact, because of the constrained possible growth of the diagonal of a rational function you can conclude that the sequence is eventually 0 (this is the case for the example `1/(1-y-x*y^3)` in your post).

Dealing with (1) involves computing a Whitney stratification of algebraic varieties. We have some (non-public) beta code that does this, which will hopefully be made public in the next few months when we are finished testing.

Once we have code for (1) then we can use similar techniques as we currently do for smooth points to verify (or rule out) which are minimal for (2). 

Characterizing critical points at infinity for (3) is a bit delicate. There is a paper that discusses one method of characterizing them and has a Maple implementation using Gröbner bases

Yuliy Baryshnikov, Stephen Melczer, Robin Pemantle (2022). Stationary points at infinity for analytic combinatorics. Foundations of Computational Mathematics, Volume 22(5), 1631–1664. 

(see the entry for this paper on https://melczer.ca/research/ for the code). We are currently working on a more efficient way of characterizing the points, and hope to have a theoretical paper out shortly. After that we hope to implement this newer approach, so (hopefully) expect something to be added to this package on the timeline of about a year to deal with critical points at infinity.

For now, if you expect your sequence is eventually zero you will probably have to show  (4) holds by hand. See Section 5.3.1 in 

https://melczer.ca/files/Melczer-SubmittedManuscript.pdf

for some results and discussion on this topic (also Section 9.3 for the critical points at infinity). If you know the theory of polynomial amoebas (also discussed in that book) that can be very useful for visualizing (or even proving) when this situation occurs.

If you want to be notified when the new theoretical work on critical points at infinity is published, or you have other theoretical questions beyond the code in this package, you can send me an email.

**Comment by RecursionSheep** [comment]
Thanks for your helpful answer!
